
* Installing Termux from scratch

** Background

I've probably reinstalled Termux twice on each Android device and then
had to fiddle a bit to get it customized. Now I tried to update my
phone and the repositories have changed since the last time I upgraded
and the termux site says to no longer use the Google Play version.

It's time to have a single place that describes the full install.

** Uninstall Play Termux

Make sure there is no version of Termux installed, perhaps from Google Play.

** Install Termux from F-Droid

F-Droid is an app store for various open source software. Install it
from here:

https://f-droid.org

then install Termux:

https://wiki.termux.com

There will be a lot of prompts to allow installation of these apps on
your phone.

Run termux then:

#+BEGIN_SRC bash
pkg upgrade
#+END_SRC

It updated a number of configuration files and I hit "Y" to accept the
new version.

** Install common dotfiles

Install git:

#+BEGIN_SRC bash
pkg install git
#+END_SRC

We will be running a variation of the commands here:

https://github.com/sizezero/dotfiles

Note the location of the git executable on the filesystem is different
so the second command is slightly different.

#+BEGIN_SRC bash
git clone --bare https://github.com/sizezero/dotfiles.git ~/.cfg
alias config='/data/data/com.termux/files/user/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
config checkout
#if the above command fails, delete or backup any conflicting files and retry
config config --local status.showUntrackedFiles no
#+END_SRC

** generate an ssh key

Pulling from github is fine but if you want to push you will need to
setup ssh access.

#+BEGIN_SRC bash
pkg install openssh
#+END_SRC

Only follow the first few instructions from:

https://github.com/sizezero/dev-notes/blob/master/using-ssh-for-github.org

These are duplicated here:

#+BEGIN_SRC bash
$ ssh-keygen -t ed25519 -C "robert@kleemann.org"
#+END_SRC

Be sure to type a passphrase that isn't too cumbersome. You will have
to type this every time you push since termux doesn't have a good,
permanent ssh agent.

This created:

#+BEGIN_SRC bash
~/.ssh/
  id_ed25519
  id_ed25519.pub
#+END_SRC

** configure github to accept the key

Install the Termux API app via F-Droid.

Then install the termux-api from within Termux:

#+BEGIN_SRC bash
pkg install termux-api
termux-clipboard-set "hello world"
#+END_SRC

Paste the "hello world" text into some android app to verify it is working.

Copy the public key to the clipboards:

#+BEGIN_SRC bash
termux-clipboard-set < ~/.ssh/id_ed25519.pub
#+END_SRC

On your phone, navigate to the github settings page. Go to the section
on ssh keys. I named mine "phone termux". Paste in the key from the
clipboard.

** install common apps

I'm not sure if I should keep this list up-to-date or just update it
every time.

#+BEGIN_SRC bash
pkg install emacs
#+END_SRC

** fix emacs

Navigate to the end of the file =~/.termux/termux.properties= and
uncomment the line:

#+BEGIN_SRC bash
ctrl-space-workaround = true
#+END_SRC

Then run:

#+BEGIN_SRC bash
termux-reload-settings
#+END_SRC

** backup and restore

There are ways to backup and restore termux that I may want to do to
prevent me from having to set this up again. On the other hand, termux
seems pretty flakey and I think it's likely that they change their
universe in a year or so making backups worthless. All my data will be
in committed and pushed github repos anyway.
